### PR TITLE
Fix pushing an URL to parseURI (AdReport Broken)

### LINKED ISSUE #126: Report an ad page doesn't work correctly
The problem seems to be in passing an invalid URL to the `parseURI` function from `adreport.js`.

### PR DESCRIPTION
**Pull request by tomasko126**
Fixes #126 

@kpeckett Another high-brio bug, could you please take a look at it?

Thanks! :)

### CODE REVIEW

File: pages/adreport.js [hunk 1]
```diff
@@ -421,17 +421,11 @@ function checkmalware() {
...
-                    var resource = key.split(":|:");
-                    if (resource &&
-                        resource.length === 2 &&
-                        extracted_domains.indexOf(new parseURI(resource[1]).hostname) === -1) {
-                        extracted_domains.push(new parseURI(resource[1]).hostname);
-                    }
-                } else {
-                    if (extracted_domains.indexOf(new parseURI(key).hostname) === -1) {
-                        extracted_domains.push(new parseURI(key).hostname);
-                    }
```
Comment (itskdog) [inline pages/adreport.js:434]: Why is the else clause no longer needed?

Comment (tomasko126) [reply pages/adreport.js:434]: @kpeckett Because we can't push `key` to parseURI anymore, since `key` looks like: `1:|:https://example.com:|:document` and that's not a valid URI -> in this case parseURI would throw an exception.

**Review by itskdog — APPROVED** [review]
